config/routes.rb
ContactsMap::Application.routes.draw do
  resources :twitter_users


  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
  match '/followers/:id.json' => 'users#followers'
end

app/models/user.rb
include ApplicationHelper
class User < ActiveRecord::Base
  attr_accessible :provider, :uid, :name, :email, :followers
  validates_presence_of :name
  has_and_belongs_to_many(:followers,
    :class_name => "User",
    :join_table => "twitterConnections",
    :foreign_key => "twitterUser_a_id",
    :association_foreign_key => "twitterUser_b_id")

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
        user.name = auth['info']['name'] || ""
        user.email = auth['info']['email'] || ""
      end
    end
  end

  def self.create_from_twitter(info)
  	puts info
    create! do |u|
      u.uid = info.id
      u.name = info.name
      u.screen_name = info.screen_name
      u.profile_image_url = info.profile_image_url.to_s
    end
  end

  def getFollowers
    client.followers(self.uid.to_i).take(20).to_a.each do |follower|
      a = User.where(:uid => follower.id).first || User.create_from_twitter(follower)
      self.followers << a unless self.followers.include? a
    end
  end

  def fetchFollowers
  	if self.followers.length < 20
  		self.getFollowers
  	end
  	self.followers
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?
  helper_method :client

  private
  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue Exception => e
      nil
    end
  end

  def user_signed_in?
    return true if current_user
  end

  def correct_user?
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url, :alert => "Access denied."
    end
  end

  def authenticate_user!
    if !current_user
      redirect_to root_url, :alert => 'You need to sign in for access to this page.'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @followers = User.find(params[:uid]).fetchFollowers
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/twitter'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
# Reset the session after successful login, per
# 2.8 Session Fixation – Countermeasures:
# http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    reset_session
    session[:user_id] = user.id
    session[:user_oauth_token] = auth['credentials']['token']
    session[:user_oauth_token_secret] = auth['credentials']['secret']
    
    puts session[:user_oauth_token]
    puts session[:user_oauth_token_secret]

    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end


  def show
    @user = User.find(params[:id])
  end

  def followers
    render json: User.find(params[:id]).fetchFollowers
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def client
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key         = ENV['OMNIAUTH_PROVIDER_KEY']
      config.consumer_secret      = ENV['OMNIAUTH_PROVIDER_SECRET']
      config.access_token         = ENV['TWITTER_ACCESS_TOKEN']
      config.access_token_secret  = ENV['TWITTER_ACCESS_SECRET']
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h3 Followers
%p
  We've scanned
  =@followers.length
  of your followers.
-@followers.each do |follower|
  .span3.text-center
    %h4=link_to follower.name, root_url(:uid => follower.id)
    =image_tag follower.profile_image_url
    =link_to "http://twitter.com/#{follower.screen_name}" do
      %h6="@#{follower.screen_name}"

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Contactsmap", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      Logged in as #{current_user.name}
    %li
      = link_to 'Logout', signout_path
  - else
    %li
      = link_to 'Login', signin_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Contactsmap"
      %meta{:content => content_for?(:description) ? yield(:description) : "Contactsmap", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/users/edit.html.haml
= form_for(@user) do |f|
  = f.label :email
  = f.text_field :email
  %br/
  = f.submit "Sign in"

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}